name = "tDigest"
uuid = "1651a0ed-c333-45c8-9516-99f2a2ddde92"
authors = ["Ted Dunning <ted.dunning@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
